### ISSUE TITLE
Missing documentation on how to load the scss

### ISSUE THREAD

**Issue by dstollie** [HarwinBorger/SpaceFramework#1]
Im missing the explanation on how to load the scss and call the appropriate functions on how to get up and running with the spaceframework. Now I had to look into the code base.

Am i doing it  right

```scss
@import '../../components/spaceframework/scss/spaceframework';
// These are my custom settings
@import 'spaceframework-settings';

@include space-init();
```

**Comment by HarwinBorger** [comment]
Hi,

Thank you for your comment. I have added a 'Getting started' section to the readme file. Which can be found here: https://github.com/HarwinBorger/SpaceFramework#getting-started 

Your example of initializing the SpaceFramework is correct. 

Regards, Harwin
