### ISSUE TITLE
Add demo page

### ISSUE THREAD

**Issue by colorcube** [HarwinBorger/SpaceFramework#29]
Interesting project but it's hard to imagine what the result looks like.

Would be nice to have a demo page. Maybe the Foundation kitchen sink? So it would be easy to compare.

**Comment by HarwinBorger** [comment]
Thank you for taking interest in the project. If you still are interested, there have been developments on the framework last couple months. You can find documentation on https://docs.spaceframework.dev and I add examples on the main website https://spaceframework.dev 

If you need more information or missing out information, let me know I will try to add it (and respond sooner ;-) )
