### ISSUE TITLE
Missing documentation of the possible settings to override

### ISSUE THREAD

**Issue by dstollie** [HarwinBorger/SpaceFramework#3]
It should be really handy if there was some kind of overview of which settings we can use to override the default behaviour.

**Comment by HarwinBorger** [comment]
Hi, 

Thanks for the feedback. I am currently working on setting up some proper documentation. Feel free to help: https://github.com/HarwinBorger/SpaceDocumentation/tree/develop

**Comment by HarwinBorger** [comment]
Hi @dstollie ,

I continued on developing the SpaceFramework, i am working on a documentation and it can be found here: https://spacerhythm.com. However it is a work in progress at the moment. Hope to finish it soon.

**Comment by HarwinBorger** [comment]
Hi it has been during a while and since my last message there is changed a lot. I am working on the documentation on: https://github.com/HarwinBorger/SpaceFramework/tree/feature/docs

**Comment by dstollie** [comment]
@HarwinBorger thanks for the update, im looking forward to some new updates

**Comment by HarwinBorger** [comment]
3 years later 😄 but: Documentation can be found on: https://docs.spaceframework.dev
